spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: dis
    password: dis
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  