spring:
  application:
    name: user-service
  cloud:
    config:
      uri: http://localhost:8888  # Config Server URL
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka  # Eureka server URL
