server:
  port: 8761  # Eureka Server runs on port 8761

spring:
  application:
    name: discovery-server

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  # Discovery Server does not register itself
    fetch-registry: false  # It does not fetch service registry
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.netflix.eureka: INFO
