spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/products
    username: dis
    password: dis
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8081

